# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Nowo\AuthKitBundle\MagicLogin\MagicLoginNotifierInterface: '@App\Identity\AuthKit\AuthKitMagicLoginMailNotifier'
    Nowo\AuthKitBundle\PasswordReset\PasswordResetNotifierInterface: '@App\Identity\AuthKit\AuthKitPasswordResetMailNotifier'
    Nowo\AuthKitBundle\DeviceIntelligence\NewDeviceLoginNotifierInterface: '@App\Identity\AuthKit\AuthKitNewDeviceLoginMailNotifier'

    Nowo\AuthKitBundle\MagicLogin\MagicLoginRequestHandler:
        arguments:
            $loginLinkHandler: '@security.authenticator.login_link_handler.main'
