# GitHub Sponsors — https://github.com/nowo-tech
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [nowo-tech]
custom: ["https://nowo.tech"]
