# yaml-language-server: $schema=../../vendor/symfony/framework-bundle/Resources/config/schema/symfony-1.0.xsd

framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: async
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000

            failed: 'doctrine://default?queue_name=failed'

            sync: 'sync://'

        routing:
            App\Ingest\Message\ProcessEnvelopeMessage: async
            App\Notifications\Message\DeliverNotificationMessage: async

when@test:
    framework:
        messenger:
            transports:
                async: 'sync://'
                failed: 'in-memory://'
