# nowo-tech/password-strength-bundle
# https://github.com/nowo-tech/PasswordStrengthBundle
nowo_password_strength:
    form_theme: '@PasswordStrengthBundle/Form/password_strength_theme_tailwind2.html.twig'
    feedback_position: below
    show_requirements: true
    live_feedback: true
    default_level: medium
    generator_mode: off
    use_password_toggle: true
    levels:
        weak:
            min_length: 6
        medium:
            min_length: 8
            require_lowercase: true
            require_uppercase: true
            require_digit: true
        strong:
            min_length: 12
            require_lowercase: true
            require_uppercase: true
            require_digit: true
            require_special: true
