# nowo-tech/password-toggle-bundle
# https://github.com/nowo-tech/PasswordToggleBundle
nowo_password_toggle:
    toggle: true
    visible_icon: 'tabler:eye-off'
    hidden_icon: 'tabler:eye'
    visible_label: 'Show password'
    hidden_label: 'Hide password'
    button_classes: ['btn-ghost', '!px-3', '!py-2', 'shrink-0']
    toggle_container_classes: ['flex', 'w-full', 'items-stretch', 'gap-2']
    use_toggle_form_theme: true
    always_empty: true
    trim: false
