framework:
    default_locale: en
    enabled_locales: [en, es, de, nl, fr, it, pt]
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
