framework:
    default_locale: '%default_locale%'
    enabled_locales: [en, es, de, nl, fr, it, pt]
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: '%fallback_locales%'
        providers:
