<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Breadcrumb Kit 2.1 — path/attribute matching columns on dashboard_breadcrumb_item.
 * Generated by nowo_breadcrumb_kit:generate-migration --update (down fixed for safety).
 */
final class Version20260804220822_CreateBreadcrumbKitTablesByConfiguration extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add path_pattern and match_attributes to dashboard_breadcrumb_item (BreadcrumbKit 2.1)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE `dashboard_breadcrumb_item` ADD path_pattern VARCHAR(512) DEFAULT NULL');
        $this->addSql('ALTER TABLE `dashboard_breadcrumb_item` ADD match_attributes JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE `dashboard_breadcrumb_item` DROP match_attributes');
        $this->addSql('ALTER TABLE `dashboard_breadcrumb_item` DROP path_pattern');
    }
}
