<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Dashboard Menu tables (menu + menu_item).
 * Generated by nowo_dashboard_menu:generate-migration.
 * Connection: default | Table prefix: (none)
 *
 * After generating this file, run migrations:
 *   php bin/console doctrine:migrations:migrate
 *
 * If you use a non-default connection, run (replace CONNECTION):
 *   php bin/console doctrine:migrations:migrate --conn=CONNECTION
 */
final class Version20260720104249_CreateDashboardMenuTablesByConfiguration extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create dashboard_menu and dashboard_menu_item tables (prefix: (none))';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE dashboard_menu (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(64) NOT NULL, attributes_key VARCHAR(512) DEFAULT \'\' NOT NULL, name VARCHAR(255) DEFAULT NULL, icon VARCHAR(128) DEFAULT NULL, class_menu VARCHAR(512) DEFAULT NULL, ul_id VARCHAR(255) DEFAULT NULL, class_item VARCHAR(512) DEFAULT NULL, class_link VARCHAR(512) DEFAULT NULL, class_children VARCHAR(512) DEFAULT NULL, class_section_children VARCHAR(512) DEFAULT NULL, class_section_child_item VARCHAR(512) DEFAULT NULL, class_section_child_link VARCHAR(512) DEFAULT NULL, class_section_label VARCHAR(512) DEFAULT NULL, class_section VARCHAR(512) DEFAULT NULL, class_divider VARCHAR(512) DEFAULT NULL, class_current VARCHAR(128) DEFAULT NULL, class_branch_expanded VARCHAR(128) DEFAULT NULL, class_has_children VARCHAR(128) DEFAULT NULL, class_expanded VARCHAR(128) DEFAULT NULL, class_collapsed VARCHAR(128) DEFAULT NULL, permission_checker VARCHAR(255) DEFAULT NULL, depth_limit INT DEFAULT NULL, collapsible TINYINT DEFAULT NULL, collapsible_expanded TINYINT DEFAULT NULL, nested_collapsible TINYINT DEFAULT NULL, nested_collapsible_sections TINYINT DEFAULT NULL, attributes JSON DEFAULT NULL, base TINYINT DEFAULT 0 NOT NULL, UNIQUE INDEX uniq_menu_code_context (code, attributes_key), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE dashboard_menu_item (id INT AUTO_INCREMENT NOT NULL, position INT DEFAULT 0 NOT NULL, label VARCHAR(255) DEFAULT NULL, translations JSON DEFAULT NULL, link_type VARCHAR(20) DEFAULT \'route\', route_name VARCHAR(255) DEFAULT NULL, route_params JSON DEFAULT NULL, external_url VARCHAR(2048) DEFAULT NULL, permission_key VARCHAR(128) DEFAULT NULL, permission_keys JSON DEFAULT NULL, is_unanimous TINYINT DEFAULT 1 NOT NULL, icon VARCHAR(128) DEFAULT NULL, item_type VARCHAR(20) DEFAULT \'link\', link_resolver VARCHAR(255) DEFAULT NULL, target_blank TINYINT DEFAULT 0 NOT NULL, section_collapsible TINYINT DEFAULT NULL, menu_id INT NOT NULL, parent_id INT DEFAULT NULL, INDEX IDX_9FA38DA3CCD7E912 (menu_id), INDEX idx_menu_position (menu_id, position), INDEX idx_parent_id (parent_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE dashboard_menu_item ADD CONSTRAINT FK_9FA38DA3CCD7E912 FOREIGN KEY (menu_id) REFERENCES dashboard_menu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dashboard_menu_item ADD CONSTRAINT FK_9FA38DA3727ACA70 FOREIGN KEY (parent_id) REFERENCES dashboard_menu_item (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();
        $this->addSql($platform->getDropTableSQL('dashboard_menu_item'));
        $this->addSql($platform->getDropTableSQL('dashboard_menu'));
    }
}
